import { useEffect, useState } from 'react';
import { View, TextInput, Image, Pressable } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useTranslation } from 'react-i18next';
import Ionicons from '@expo/vector-icons/Ionicons';
import { AppHeader, Card, Copy, Heading, Label, Action, Notice, StitchPage, stitchStyles as u } from '@/components/ui/Stitch';
import { colors } from '@/theme/tokens';
import { runtime } from '@/config/runtime';

export default function PhoneAccessScreen({initialStep=1}:{initialStep?:number}) {
  const {t}=useTranslation(); const router=useRouter(); const params=useLocalSearchParams<{phone?:string}>();
  const [step,setStep]=useState(initialStep); const [phone,setPhone]=useState(params.phone?.replace(/^\+243/,'')??''); const [otp,setOtp]=useState(''); const [timer,setTimer]=useState(48); const [message,setMessage]=useState(false);
  useEffect(()=>{if(step!==2)return; const interval=setInterval(()=>setTimer(v=>Math.max(0,v-1)),1000);return()=>clearInterval(interval);},[step]);
  return <View style={{flex:1,backgroundColor:'white'}}><AppHeader subtitle={t('stitch.platform')}/><StitchPage>
    <Image source={require('../../../assets/brand-wordmark.png')} style={{width:'100%',height:66,marginTop:12,marginBottom:8}} resizeMode="contain" accessibilityLabel="AutoGuardian"/>
    <View style={{gap:8}}><Heading style={{fontSize:25,lineHeight:32}}>{t('stitch.protect')}</Heading><Copy style={[u.muted,{fontSize:15,lineHeight:24}]}>{t('stitch.protectBody')}</Copy></View>
    <View style={[u.inset,{flexDirection:'row',padding:4,marginTop:8}]}>{[1,2].map(i=><Pressable key={i} accessibilityRole="tab" accessibilityState={{selected:step===i}} disabled={i===2&&phone.replace(/\D/g,'').length<9} onPress={()=>setStep(i)} style={{flex:1,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,minHeight:42,backgroundColor:step===i?'white':'transparent',borderRadius:4}}><View style={{width:18,height:18,borderRadius:9,backgroundColor:step===i?colors.primary:colors.border,alignItems:'center',justifyContent:'center'}}><Copy style={{fontSize:11,lineHeight:16,color:step===i?'white':colors.primary}}>{i}</Copy></View><Label style={{color:step===i?colors.primary:colors.textMuted}}>{t(i===1?'stitch.phone':'stitch.otp')}</Label></Pressable>)}</View>
    {step===1?<><Card><Label>{t('stitch.phoneLabel')}</Label><View style={u.row}><View style={[u.inset,{minHeight:48,justifyContent:'center'}]}><Label>🇨🇩 +243</Label></View><TextInput accessibilityLabel={t('stitch.phoneLabel')} style={[u.input,{flex:1}]} value={phone} onChangeText={value=>setPhone(value.replace(/[^0-9 ]/g,''))} placeholder="81 234 5678" placeholderTextColor={colors.textMuted} keyboardType="phone-pad" maxLength={13}/></View><View style={[u.row,{alignItems:'flex-start'}]}><Ionicons name="information-circle-outline" size={18} color={colors.textMuted}/><Copy style={[u.muted,{flex:1}]}>{t('stitch.smsHint')}</Copy></View></Card><Action label={t('stitch.sendCode')} icon="arrow-forward" disabled={phone.replace(/\D/g,'').length<9||!runtime.isDemo} onPress={()=>{setStep(2);setTimer(48);setMessage(true);}}/></>:<Card><View style={u.between}><Label>{t('stitch.code')}</Label><Pressable accessibilityRole="button" onPress={()=>setStep(1)} style={{minHeight:40,justifyContent:'center'}}><Copy style={{fontSize:12,color:colors.primary}}>{t('stitch.editNumber')}</Copy></Pressable></View><Copy style={u.muted}>+243 {phone}</Copy><TextInput accessibilityLabel={t('stitch.code')} value={otp} onChangeText={value=>setOtp(value.replace(/\D/g,''))} maxLength={6} keyboardType="number-pad" style={[u.input,{textAlign:'center',fontSize:25,letterSpacing:12}]} placeholder="••••••" placeholderTextColor={colors.border}/><View style={u.between}><Copy style={{fontSize:12,color:colors.textMuted}}>{t('stitch.resendIn')} 0:{String(timer).padStart(2,'0')}</Copy><Pressable accessibilityRole="button" disabled={timer>0} onPress={()=>{setTimer(48);setMessage(true);}} style={{minHeight:40,justifyContent:'center',opacity:timer>0?0.4:1}}><Label>{t('stitch.resend')}</Label></Pressable></View><Notice icon="lock-closed-outline">{t('stitch.codeHint')}</Notice><Action label={t('stitch.verify')} icon="checkmark-circle-outline" disabled={otp.length!==6||!runtime.isDemo} onPress={()=>router.push('/(auth)/terms')}/></Card>}
    {message&&<Copy style={{fontSize:12,color:colors.warning}}>{t('stitch.noSms')}</Copy>}
    <View style={{flexDirection:'row',gap:10,marginTop:8}}>{(['antiFraud','instantAlert'] as const).map((key,i)=><View key={key} style={[u.inset,{flex:1}]}><View style={u.row}><Ionicons name={i===0?'shield-checkmark-outline':'notifications-outline'} size={19} color={colors.primary}/><Label style={{flex:1,fontSize:12}}>{t('stitch.'+key)}</Label></View><Copy style={{fontSize:12,lineHeight:18,color:colors.textMuted}}>{t('stitch.'+key+'Body')}</Copy></View>)}</View>
    <Pressable accessibilityRole="button" onPress={()=>router.push('/(auth)/terms')} style={{minHeight:48,justifyContent:'center',marginTop:24}}><Copy style={{fontSize:12,textAlign:'center',color:colors.textMuted}}>{t('stitch.terms')}</Copy></Pressable><Notice icon="shield-half-outline">{t('stitch.securityRule')}</Notice>
    {runtime.isDemo&&<Copy style={{fontSize:11,color:colors.textMuted,textAlign:'center'}}>{t('stitch.preview')}</Copy>}
  </StitchPage></View>;
}
