export const flowEn={
  feeTitle:'Verification fee', feeBody:'Review the configured service fee before continuing.', free:'Free checks remaining', fee:'Verification fee', feeHint:'Sample amount only. No money is collected in this preview.', continue:'Continue', payment:'Payment', paymentBody:'Choose a configured payment method for the verification service.', mobileMoney:'Mobile money', card:'Card · provider not connected', simulate:'Preview payment', simulated:'Simulated payment', simulatedBody:'No money was collected and no provider confirmed a transaction.', status:'View status', paymentPending:'Payment confirmation pending',
  waiting:'Waiting for the owner', waitingBody:'Example verification request. Owner confirmation is required for this transaction.', scenarios:'Preview outcomes', confirmed:'Sale confirmed', confirmedBody:'Example: the owner authorized this individual transaction for its configured validity.', denied:'Sale not confirmed', deniedBody:'Example: the owner explicitly refused this transaction. Do not pay the seller.', no_response:'No response', no_responseBody:'Example: the owner did not respond. Silence does not grant permission to sell.', expired:'Confirmation expired', expiredBody:'Example: the confirmation validity ended. A new check is required.', missing:'Reported missing', missingBody:'Example: the vehicle is reported missing. Do not pay. Contact the police.', unknown:'Status unavailable', unknownBody:'The current transaction status could not be determined.', result:'Verification result', home:'Back to Check',
  saleStatus:'Resale status', renewal:'Renewal date', seals:'Seal record', sealBody:'Seal identifiers only. Confidential alarm positions are not shown.', list:'List for sale', listingBody:'A listing indicates availability. The owner still confirms each transaction.', duration:'Duration (days)', pin:'Owner PIN', listingHint:'The listing expires after its configured duration and returns to NOT FOR SALE.', submitListing:'Preview listing', listingPreview:'Preview only. No listing was changed and no PIN was verified.',
  terms:'Terms & data consent', termsBody:'The authority’s approved terms and data notice must be supplied before real account registration.', termsSample:'Design preview only. AutoGuardian checks enrolled vehicle records and requests owner confirmation; enrollment does not certify legal title.', consent:'I have reviewed this preview notice', pinSetup:'Create owner PIN', pinConfirm:'Confirm owner PIN', pinBody:'Use 4–6 digits for sensitive actions.', confirmBody:'Enter the same PIN again.', pinMismatch:'The PINs do not match. Try again.', setup:'Complete preview setup', pinNotice:'Preview only. This PIN is not stored or registered with a server.', scan:'Scan seal QR', scanBody:'Place the physical seal QR code inside the frame.', unavailable:'Camera scanning is not connected in this frontend preview. Enter the code manually.', manual:'Manual seal code', useCode:'Use this code',
};
export const flowFr={
  feeTitle:'Frais de vérification', feeBody:'Consultez les frais configurés avant de continuer.', free:'Vérifications gratuites restantes', fee:'Frais de vérification', feeHint:'Montant fictif. Aucun paiement dans cet aperçu.', continue:'Continuer', payment:'Paiement', paymentBody:'Choisissez un moyen de paiement configuré pour la vérification.', mobileMoney:'Mobile money', card:'Carte · prestataire non connecté', simulate:'Simuler le paiement', simulated:'Paiement simulé', simulatedBody:'Aucun montant prélevé et aucune transaction confirmée par un prestataire.', status:'Voir le statut', paymentPending:'Confirmation du paiement en attente',
  waiting:'En attente du propriétaire', waitingBody:'Demande fictive. La confirmation du propriétaire est requise pour cette transaction.', scenarios:'Résultats fictifs', confirmed:'Vente confirmée', confirmedBody:'Exemple : le propriétaire a autorisé cette transaction pour sa validité configurée.', denied:'Vente non confirmée', deniedBody:'Exemple : le propriétaire a refusé cette transaction. Ne payez pas le vendeur.', no_response:'Sans réponse', no_responseBody:'Exemple : le propriétaire n’a pas répondu. Le silence n’autorise pas la vente.', expired:'Confirmation expirée', expiredBody:'Exemple : la validité a expiré. Une nouvelle vérification est requise.', missing:'Véhicule signalé disparu', missingBody:'Exemple : véhicule signalé disparu. Ne payez pas. Contactez la police.', unknown:'Statut indisponible', unknownBody:'Le statut actuel de cette transaction ne peut pas être déterminé.', result:'Résultat de vérification', home:'Retour à la vérification',
  saleStatus:'Statut de revente', renewal:'Renouvellement', seals:'Dossier des scellés', sealBody:'Identifiants uniquement. Les positions confidentielles des alarmes ne sont pas affichées.', list:'Mettre en vente', listingBody:'Une annonce indique la disponibilité. Le propriétaire confirme chaque transaction.', duration:'Durée (jours)', pin:'PIN propriétaire', listingHint:'L’annonce expire après sa durée configurée et revient au statut PAS À VENDRE.', submitListing:'Simuler l’annonce', listingPreview:'Aperçu uniquement. Aucune annonce modifiée et aucun PIN vérifié.',
  terms:'Conditions et consentement', termsBody:'Les conditions et la notice approuvées doivent être fournies avant toute inscription réelle.', termsSample:'Aperçu uniquement. AutoGuardian vérifie les dossiers enrôlés et demande la confirmation du propriétaire. L’enrôlement ne certifie pas le titre légal.', consent:'J’ai consulté cette notice fictive', pinSetup:'Créer le PIN propriétaire', pinConfirm:'Confirmer le PIN', pinBody:'Utilisez 4 à 6 chiffres pour les actions sensibles.', confirmBody:'Saisissez le même PIN.', pinMismatch:'Les PIN ne correspondent pas. Réessayez.', setup:'Terminer la configuration fictive', pinNotice:'Aperçu uniquement. Aucun PIN stocké ni enregistré sur le serveur.', scan:'Scanner le QR du scellé', scanBody:'Placez le QR du scellé physique dans le cadre.', unavailable:'La caméra n’est pas connectée dans cet aperçu. Saisissez le code manuellement.', manual:'Code manuel du scellé', useCode:'Utiliser ce code',
};
