import { useState } from 'react';
import { View, TextInput } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useTranslation } from 'react-i18next';
import Ionicons from '@expo/vector-icons/Ionicons';
import { Card, Copy, Heading, Label, Action, Notice, Progress, DetailRow, StitchPage, stitchStyles as u } from '@/components/ui/Stitch';
import { colors } from '@/theme/tokens';
import { runtime } from '@/config/runtime';

export function FeeSummaryScreen() {
  const {t}=useTranslation();const router=useRouter();const {id,type}=useLocalSearchParams<{id:string;type:string}>();
  return <StitchPage><Heading>{t('flow.feeTitle')}</Heading><Copy style={u.muted}>{t('flow.feeBody')}</Copy><Card><View style={u.row}><Ionicons name="receipt-outline" size={22} color={colors.primary}/><Label>{t('stitch.activeQuery')}</Label></View><DetailRow label={t('stitch.identifier')} value={id??'1842AA10'}/><DetailRow label={t('flow.free')} value="0"/><View style={u.between}><Label>{t('flow.fee')}</Label><Heading>$2.00 USD</Heading></View></Card><Notice tone="warning">{t('flow.feeHint')}</Notice><Action label={t('flow.continue')} icon="arrow-forward" onPress={()=>router.push({pathname:'/(consumer)/payment',params:{id,type,amount:'2.00'}})}/><Action secondary label={t('stitch.cancel')} onPress={()=>router.back()}/></StitchPage>;
}
export function PaymentScreen() {
  const {t}=useTranslation();const router=useRouter();const {id,type}=useLocalSearchParams<{id:string;type:string}>(); const [simulated,setSimulated]=useState(false);
  return <StitchPage><Heading>{t(simulated?'flow.simulated':'flow.payment')}</Heading><Copy style={u.muted}>{t(simulated?'flow.simulatedBody':'flow.paymentBody')}</Copy><Card><DetailRow label={t('stitch.identifier')} value={id??'1842AA10'}/><DetailRow label={t('flow.fee')} value="$2.00 USD"/></Card>{!simulated&&<><Card style={{borderColor:colors.primary}}><View style={u.between}><View style={u.row}><Ionicons name="phone-portrait-outline" size={22} color={colors.primary}/><Label>{t('flow.mobileMoney')}</Label></View><Ionicons name="radio-button-on" size={20} color={colors.primary}/></View></Card><Card style={{opacity:0.5}}><View style={u.row}><Ionicons name="card-outline" size={22} color={colors.textMuted}/><Copy>{t('flow.card')}</Copy></View></Card></>}<Notice tone="warning">{t('flow.feeHint')}</Notice><Action icon={simulated?'arrow-forward':'cash-outline'} label={t(simulated?'flow.status':'flow.simulate')} onPress={()=>{if(!runtime.isDemo)return;if(simulated)router.push({pathname:'/(consumer)/waiting',params:{id,type}});else setSimulated(true);}}/><Action secondary label={t('stitch.cancel')} onPress={()=>router.back()}/></StitchPage>;
}
export function WaitingScreen() {
  const {t}=useTranslation();const router=useRouter();const {id,type}=useLocalSearchParams<{id:string;type:string}>();const [refreshed,setRefreshed]=useState(false);
  return <StitchPage><Heading>{t('flow.waiting')}</Heading><Copy style={u.muted}>{t('flow.waitingBody')}</Copy><Card><DetailRow label={t('stitch.identifier')} value={id??'1842AA10'}/><View style={u.between}><View style={u.row}><Ionicons name="hourglass-outline" size={21} color={colors.warning}/><Label>{t('stitch.waiting')}</Label></View><Copy style={{color:colors.warning,fontSize:12}}>04:32</Copy></View><Progress value={45}/><Notice tone="warning">{t('stitch.silence')}</Notice><Copy style={{fontSize:12,color:colors.success}}>{t('stitch.notified')}</Copy><Action secondary icon="refresh-outline" label={t(refreshed?'stitch.refreshed':'stitch.refresh')} onPress={()=>setRefreshed(true)}/></Card><Notice tone="danger" icon="shield-half-outline">{t('stitch.safety')}</Notice>{runtime.isDemo&&<Card><Label>{t('flow.scenarios')}</Label>{['confirmed','denied','no_response','expired','missing'].map(result=><Action key={result} secondary label={t('flow.'+result)} onPress={()=>router.replace({pathname:'/(consumer)/outcome',params:{id,type,result}})}/>)}</Card>}</StitchPage>;
}
export function OutcomeScreen() {
  const {t}=useTranslation();const router=useRouter();const {id,result}=useLocalSearchParams<{id:string;result:string}>(); const known=['confirmed','denied','no_response','expired','missing'];const key=known.includes(result)?result:'unknown';
  const tint=key==='confirmed'?colors.success:key==='denied'||key==='missing'?colors.danger:colors.warning;
  return <StitchPage><Heading>{t('flow.result')}</Heading><Card style={{borderColor:tint,borderTopWidth:4}}><View style={u.row}><Ionicons name={key==='confirmed'?'checkmark-circle-outline':key==='denied'?'close-circle-outline':'time-outline'} size={32} color={tint}/><Heading style={{color:tint,fontSize:18,flex:1}}>{t('flow.'+key)}</Heading></View><Copy>{t('flow.'+key+'Body')}</Copy><DetailRow label={t('stitch.identifier')} value={id??'1842AA10'}/><Copy style={{fontSize:11,color:colors.textMuted}}>{t('stitch.preview')}</Copy></Card><Notice tone="danger" icon="shield-half-outline">{t('stitch.safety')}</Notice><Action label={t('flow.home')} onPress={()=>router.replace('/(consumer)')}/></StitchPage>;
}
export function VehicleDetailScreen() {
  const {t}=useTranslation();const router=useRouter();const {id}=useLocalSearchParams<{id:string}>();const [notice,setNotice]=useState(false);const second=id==='2';
  return <StitchPage><Heading>{second?'Ford Ranger (2021)':'Toyota Land Cruiser Prado (2020)'}</Heading><Card><View style={u.between}><Ionicons name="car-outline" size={32} color={colors.primary}/><Heading style={{letterSpacing:1}}>{second?'9876CD02':'1842AA10'}</Heading></View><DetailRow label={t('flow.saleStatus')} value={t(second?'stitch.forSale':'stitch.notForSale')}/><DetailRow label={t('stitch.subscription')} value={t(second?'stitch.overdue':'stitch.active')}/><DetailRow label={t('flow.renewal')} value="01/01/2027"/></Card><Card><Heading style={{fontSize:17}}>{t('flow.seals')}</Heading><Copy style={u.muted}>{t('flow.sealBody')}</Copy>{['AG-KIN-88219','AG-KIN-88220','AG-KIN-88221','AG-KIN-88222'].map((code,i)=><DetailRow key={code} label={`${t('stitch.seal')} ${i+1}`} value={code}/>)}</Card><Action label={t('flow.list')} onPress={()=>router.push({pathname:'/(consumer)/list-for-sale',params:{id}})}/><Action danger label={t('stitch.reportMissing')} icon="warning-outline" onPress={()=>setNotice(true)}/>{notice&&<Notice>{t('stitch.missingUnavailable')}</Notice>}</StitchPage>;
}
export function ListForSaleScreen() {
  const {t}=useTranslation();const router=useRouter();const [duration,setDuration]=useState('7');const [pin,setPin]=useState('');const [submitted,setSubmitted]=useState(false);
  return <StitchPage><Heading>{t('flow.list')}</Heading><Copy style={u.muted}>{t('flow.listingBody')}</Copy><Notice tone="warning">{t('flow.listingHint')}</Notice><Card><Label>{t('flow.duration')}</Label><TextInput value={duration} onChangeText={v=>setDuration(v.replace(/\D/g,''))} keyboardType="number-pad" maxLength={2} style={u.input}/><Label>{t('flow.pin')}</Label><TextInput value={pin} onChangeText={v=>setPin(v.replace(/\D/g,''))} keyboardType="number-pad" maxLength={6} secureTextEntry style={[u.input,{letterSpacing:8,textAlign:'center'}]}/><Action label={t('flow.submitListing')} disabled={pin.length<4||Number(duration)<1} onPress={()=>{setSubmitted(true);setPin('');}}/></Card>{submitted&&<Notice>{t('flow.listingPreview')}</Notice>}<Action secondary label={t('stitch.cancel')} onPress={()=>router.back()}/></StitchPage>;
}
export function ScanScreen() {
  const {t}=useTranslation();const router=useRouter();const [code,setCode]=useState('');
  return <StitchPage><Heading>{t('flow.scan')}</Heading><Copy style={u.muted}>{t('flow.scanBody')}</Copy><View style={{minHeight:220,backgroundColor:colors.primary,borderRadius:8,alignItems:'center',justifyContent:'center'}}><View style={{borderWidth:2,borderColor:colors.accent,borderRadius:8,padding:36}}><Ionicons name="qr-code-outline" size={64} color="white"/></View></View><Notice>{t('flow.unavailable')}</Notice><Card><Label>{t('flow.manual')}</Label><TextInput value={code} onChangeText={setCode} autoCapitalize="characters" style={u.input}/><Action label={t('flow.useCode')} disabled={code.trim().length<4} onPress={()=>router.replace({pathname:'/(consumer)',params:{sealCode:code}})}/></Card></StitchPage>;
}
